// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AccessLogGrpcServiceApplyConfiguration represents a declarative configuration of the AccessLogGrpcService type for use
// with apply.
type AccessLogGrpcServiceApplyConfiguration struct {
	CommonAccessLogGrpcServiceApplyConfiguration `json:",inline"`
	AdditionalRequestHeadersToLog                []string `json:"additionalRequestHeadersToLog,omitempty"`
	AdditionalResponseHeadersToLog               []string `json:"additionalResponseHeadersToLog,omitempty"`
	AdditionalResponseTrailersToLog              []string `json:"additionalResponseTrailersToLog,omitempty"`
}

// AccessLogGrpcServiceApplyConfiguration constructs a declarative configuration of the AccessLogGrpcService type for use with
// apply.
func AccessLogGrpcService() *AccessLogGrpcServiceApplyConfiguration {
	return &AccessLogGrpcServiceApplyConfiguration{}
}

// WithAdditionalRequestHeadersToLog adds the given value to the AdditionalRequestHeadersToLog field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalRequestHeadersToLog field.
func (b *AccessLogGrpcServiceApplyConfiguration) WithAdditionalRequestHeadersToLog(values ...string) *AccessLogGrpcServiceApplyConfiguration {
	for i := range values {
		b.AdditionalRequestHeadersToLog = append(b.AdditionalRequestHeadersToLog, values[i])
	}
	return b
}

// WithAdditionalResponseHeadersToLog adds the given value to the AdditionalResponseHeadersToLog field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalResponseHeadersToLog field.
func (b *AccessLogGrpcServiceApplyConfiguration) WithAdditionalResponseHeadersToLog(values ...string) *AccessLogGrpcServiceApplyConfiguration {
	for i := range values {
		b.AdditionalResponseHeadersToLog = append(b.AdditionalResponseHeadersToLog, values[i])
	}
	return b
}

// WithAdditionalResponseTrailersToLog adds the given value to the AdditionalResponseTrailersToLog field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalResponseTrailersToLog field.
func (b *AccessLogGrpcServiceApplyConfiguration) WithAdditionalResponseTrailersToLog(values ...string) *AccessLogGrpcServiceApplyConfiguration {
	for i := range values {
		b.AdditionalResponseTrailersToLog = append(b.AdditionalResponseTrailersToLog, values[i])
	}
	return b
}
