// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// BackendProxyProtocolApplyConfiguration represents a declarative configuration of the BackendProxyProtocol type for use
// with apply.
type BackendProxyProtocolApplyConfiguration struct {
	Version *apiv1alpha1.ProxyProtocolVersion `json:"version,omitempty"`
}

// BackendProxyProtocolApplyConfiguration constructs a declarative configuration of the BackendProxyProtocol type for use with
// apply.
func BackendProxyProtocol() *BackendProxyProtocolApplyConfiguration {
	return &BackendProxyProtocolApplyConfiguration{}
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *BackendProxyProtocolApplyConfiguration) WithVersion(value apiv1alpha1.ProxyProtocolVersion) *BackendProxyProtocolApplyConfiguration {
	b.Version = &value
	return b
}
