// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CommonAccessLogGrpcServiceApplyConfiguration represents a declarative configuration of the CommonAccessLogGrpcService type for use
// with apply.
type CommonAccessLogGrpcServiceApplyConfiguration struct {
	CommonGrpcServiceApplyConfiguration `json:",inline"`
	LogName                             *string `json:"logName,omitempty"`
}

// CommonAccessLogGrpcServiceApplyConfiguration constructs a declarative configuration of the CommonAccessLogGrpcService type for use with
// apply.
func CommonAccessLogGrpcService() *CommonAccessLogGrpcServiceApplyConfiguration {
	return &CommonAccessLogGrpcServiceApplyConfiguration{}
}

// WithLogName sets the LogName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogName field is set to the value of the last call.
func (b *CommonAccessLogGrpcServiceApplyConfiguration) WithLogName(value string) *CommonAccessLogGrpcServiceApplyConfiguration {
	b.LogName = &value
	return b
}
