// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CustomTagLiteralApplyConfiguration represents a declarative configuration of the CustomTagLiteral type for use
// with apply.
type CustomTagLiteralApplyConfiguration struct {
	Value *string `json:"value,omitempty"`
}

// CustomTagLiteralApplyConfiguration constructs a declarative configuration of the CustomTagLiteral type for use with
// apply.
func CustomTagLiteral() *CustomTagLiteralApplyConfiguration {
	return &CustomTagLiteralApplyConfiguration{}
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *CustomTagLiteralApplyConfiguration) WithValue(value string) *CustomTagLiteralApplyConfiguration {
	b.Value = &value
	return b
}
