// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CustomTagHeaderApplyConfiguration represents a declarative configuration of the CustomTagHeader type for use
// with apply.
type CustomTagHeaderApplyConfiguration struct {
	Name         *string `json:"name,omitempty"`
	DefaultValue *string `json:"defaultValue,omitempty"`
}

// CustomTagHeaderApplyConfiguration constructs a declarative configuration of the CustomTagHeader type for use with
// apply.
func CustomTagHeader() *CustomTagHeaderApplyConfiguration {
	return &CustomTagHeaderApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CustomTagHeaderApplyConfiguration) WithName(value string) *CustomTagHeaderApplyConfiguration {
	b.Name = &value
	return b
}

// WithDefaultValue sets the DefaultValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultValue field is set to the value of the last call.
func (b *CustomTagHeaderApplyConfiguration) WithDefaultValue(value string) *CustomTagHeaderApplyConfiguration {
	b.DefaultValue = &value
	return b
}
