// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// CustomTagMetadataApplyConfiguration represents a declarative configuration of the CustomTagMetadata type for use
// with apply.
type CustomTagMetadataApplyConfiguration struct {
	Kind         *apiv1alpha1.MetadataKind      `json:"kind,omitempty"`
	MetadataKey  *MetadataKeyApplyConfiguration `json:"metadataKey,omitempty"`
	DefaultValue *string                        `json:"defaultValue,omitempty"`
}

// CustomTagMetadataApplyConfiguration constructs a declarative configuration of the CustomTagMetadata type for use with
// apply.
func CustomTagMetadata() *CustomTagMetadataApplyConfiguration {
	return &CustomTagMetadataApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *CustomTagMetadataApplyConfiguration) WithKind(value apiv1alpha1.MetadataKind) *CustomTagMetadataApplyConfiguration {
	b.Kind = &value
	return b
}

// WithMetadataKey sets the MetadataKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetadataKey field is set to the value of the last call.
func (b *CustomTagMetadataApplyConfiguration) WithMetadataKey(value *MetadataKeyApplyConfiguration) *CustomTagMetadataApplyConfiguration {
	b.MetadataKey = value
	return b
}

// WithDefaultValue sets the DefaultValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultValue field is set to the value of the last call.
func (b *CustomTagMetadataApplyConfiguration) WithDefaultValue(value string) *CustomTagMetadataApplyConfiguration {
	b.DefaultValue = &value
	return b
}
