// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CustomTagEnvironmentApplyConfiguration represents a declarative configuration of the CustomTagEnvironment type for use
// with apply.
type CustomTagEnvironmentApplyConfiguration struct {
	Name         *string `json:"name,omitempty"`
	DefaultValue *string `json:"defaultValue,omitempty"`
}

// CustomTagEnvironmentApplyConfiguration constructs a declarative configuration of the CustomTagEnvironment type for use with
// apply.
func CustomTagEnvironment() *CustomTagEnvironmentApplyConfiguration {
	return &CustomTagEnvironmentApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CustomTagEnvironmentApplyConfiguration) WithName(value string) *CustomTagEnvironmentApplyConfiguration {
	b.Name = &value
	return b
}

// WithDefaultValue sets the DefaultValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultValue field is set to the value of the last call.
func (b *CustomTagEnvironmentApplyConfiguration) WithDefaultValue(value string) *CustomTagEnvironmentApplyConfiguration {
	b.DefaultValue = &value
	return b
}
