// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CustomTagApplyConfiguration represents a declarative configuration of the CustomTag type for use
// with apply.
type CustomTagApplyConfiguration struct {
	Tag           *string                                 `json:"tag,omitempty"`
	Literal       *CustomTagLiteralApplyConfiguration     `json:"literal,omitempty"`
	Environment   *CustomTagEnvironmentApplyConfiguration `json:"environment,omitempty"`
	RequestHeader *CustomTagHeaderApplyConfiguration      `json:"RequestHeader,omitempty"`
	Metadata      *CustomTagMetadataApplyConfiguration    `json:"metadata,omitempty"`
}

// CustomTagApplyConfiguration constructs a declarative configuration of the CustomTag type for use with
// apply.
func CustomTag() *CustomTagApplyConfiguration {
	return &CustomTagApplyConfiguration{}
}

// WithTag sets the Tag field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tag field is set to the value of the last call.
func (b *CustomTagApplyConfiguration) WithTag(value string) *CustomTagApplyConfiguration {
	b.Tag = &value
	return b
}

// WithLiteral sets the Literal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Literal field is set to the value of the last call.
func (b *CustomTagApplyConfiguration) WithLiteral(value *CustomTagLiteralApplyConfiguration) *CustomTagApplyConfiguration {
	b.Literal = value
	return b
}

// WithEnvironment sets the Environment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Environment field is set to the value of the last call.
func (b *CustomTagApplyConfiguration) WithEnvironment(value *CustomTagEnvironmentApplyConfiguration) *CustomTagApplyConfiguration {
	b.Environment = value
	return b
}

// WithRequestHeader sets the RequestHeader field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestHeader field is set to the value of the last call.
func (b *CustomTagApplyConfiguration) WithRequestHeader(value *CustomTagHeaderApplyConfiguration) *CustomTagApplyConfiguration {
	b.RequestHeader = value
	return b
}

// WithMetadata sets the Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metadata field is set to the value of the last call.
func (b *CustomTagApplyConfiguration) WithMetadata(value *CustomTagMetadataApplyConfiguration) *CustomTagApplyConfiguration {
	b.Metadata = value
	return b
}
