// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ProviderApplyConfiguration represents a declarative configuration of the Provider type for use
// with apply.
type ProviderApplyConfiguration struct {
	OpenTelemetryConfig *OpenTelemetryTracingConfigApplyConfiguration `json:"openTelemetryConfig,omitempty"`
}

// ProviderApplyConfiguration constructs a declarative configuration of the Provider type for use with
// apply.
func Provider() *ProviderApplyConfiguration {
	return &ProviderApplyConfiguration{}
}

// WithOpenTelemetryConfig sets the OpenTelemetryConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpenTelemetryConfig field is set to the value of the last call.
func (b *ProviderApplyConfiguration) WithOpenTelemetryConfig(value *OpenTelemetryTracingConfigApplyConfiguration) *ProviderApplyConfiguration {
	b.OpenTelemetryConfig = value
	return b
}
