// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ProviderApplyConfiguration represents a declarative configuration of the Provider type for use
// with apply.
type ProviderApplyConfiguration struct {
	OpenTelemetry *OpenTelemetryTracingConfigApplyConfiguration `json:"openTelemetry,omitempty"`
}

// ProviderApplyConfiguration constructs a declarative configuration of the Provider type for use with
// apply.
func Provider() *ProviderApplyConfiguration {
	return &ProviderApplyConfiguration{}
}

// WithOpenTelemetry sets the OpenTelemetry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OpenTelemetry field is set to the value of the last call.
func (b *ProviderApplyConfiguration) WithOpenTelemetry(value *OpenTelemetryTracingConfigApplyConfiguration) *ProviderApplyConfiguration {
	b.OpenTelemetry = value
	return b
}
