// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ProxyProtocolKeyValuePairApplyConfiguration represents a declarative configuration of the ProxyProtocolKeyValuePair type for use
// with apply.
type ProxyProtocolKeyValuePairApplyConfiguration struct {
	MetadataNamespace *string `json:"metadataNamespace,omitempty"`
	Key               *string `json:"key,omitempty"`
}

// ProxyProtocolKeyValuePairApplyConfiguration constructs a declarative configuration of the ProxyProtocolKeyValuePair type for use with
// apply.
func ProxyProtocolKeyValuePair() *ProxyProtocolKeyValuePairApplyConfiguration {
	return &ProxyProtocolKeyValuePairApplyConfiguration{}
}

// WithMetadataNamespace sets the MetadataNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetadataNamespace field is set to the value of the last call.
func (b *ProxyProtocolKeyValuePairApplyConfiguration) WithMetadataNamespace(value string) *ProxyProtocolKeyValuePairApplyConfiguration {
	b.MetadataNamespace = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *ProxyProtocolKeyValuePairApplyConfiguration) WithKey(value string) *ProxyProtocolKeyValuePairApplyConfiguration {
	b.Key = &value
	return b
}
