// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ProxyProtocolRuleApplyConfiguration represents a declarative configuration of the ProxyProtocolRule type for use
// with apply.
type ProxyProtocolRuleApplyConfiguration struct {
	TlvType      *uint32                                      `json:"tlvType,omitempty"`
	OnTlvPresent *ProxyProtocolKeyValuePairApplyConfiguration `json:"onTlvPresent,omitempty"`
}

// ProxyProtocolRuleApplyConfiguration constructs a declarative configuration of the ProxyProtocolRule type for use with
// apply.
func ProxyProtocolRule() *ProxyProtocolRuleApplyConfiguration {
	return &ProxyProtocolRuleApplyConfiguration{}
}

// WithTlvType sets the TlvType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TlvType field is set to the value of the last call.
func (b *ProxyProtocolRuleApplyConfiguration) WithTlvType(value uint32) *ProxyProtocolRuleApplyConfiguration {
	b.TlvType = &value
	return b
}

// WithOnTlvPresent sets the OnTlvPresent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OnTlvPresent field is set to the value of the last call.
func (b *ProxyProtocolRuleApplyConfiguration) WithOnTlvPresent(value *ProxyProtocolKeyValuePairApplyConfiguration) *ProxyProtocolRuleApplyConfiguration {
	b.OnTlvPresent = value
	return b
}
