// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RbacPolicyApplyConfiguration represents a declarative configuration of the RbacPolicy type for use
// with apply.
type RbacPolicyApplyConfiguration struct {
	CelMatchExpression []string `json:"matchExpressions,omitempty"`
}

// RbacPolicyApplyConfiguration constructs a declarative configuration of the RbacPolicy type for use with
// apply.
func RbacPolicy() *RbacPolicyApplyConfiguration {
	return &RbacPolicyApplyConfiguration{}
}

// WithCelMatchExpression adds the given value to the CelMatchExpression field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CelMatchExpression field.
func (b *RbacPolicyApplyConfiguration) WithCelMatchExpression(values ...string) *RbacPolicyApplyConfiguration {
	for i := range values {
		b.CelMatchExpression = append(b.CelMatchExpression, values[i])
	}
	return b
}
