// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// RBACApplyConfiguration represents a declarative configuration of the RBAC type for use
// with apply.
type RBACApplyConfiguration struct {
	Policies []RBACPolicyApplyConfiguration         `json:"policies,omitempty"`
	Action   *apiv1alpha1.AuthorizationPolicyAction `json:"action,omitempty"`
	Disable  *apiv1alpha1.PolicyDisable             `json:"disable,omitempty"`
}

// RBACApplyConfiguration constructs a declarative configuration of the RBAC type for use with
// apply.
func RBAC() *RBACApplyConfiguration {
	return &RBACApplyConfiguration{}
}

// WithPolicies adds the given value to the Policies field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Policies field.
func (b *RBACApplyConfiguration) WithPolicies(values ...*RBACPolicyApplyConfiguration) *RBACApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPolicies")
		}
		b.Policies = append(b.Policies, *values[i])
	}
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *RBACApplyConfiguration) WithAction(value apiv1alpha1.AuthorizationPolicyAction) *RBACApplyConfiguration {
	b.Action = &value
	return b
}

// WithDisable sets the Disable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Disable field is set to the value of the last call.
func (b *RBACApplyConfiguration) WithDisable(value apiv1alpha1.PolicyDisable) *RBACApplyConfiguration {
	b.Disable = &value
	return b
}
