---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: gwtest
spec:
  gatewayClassName: kgateway
  listeners:
  - name: http
    port: 8080
    protocol: HTTP
    hostname: www.example.com
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: invalid-regex-route
  namespace: gwtest
spec:
  parentRefs:
  - name: example-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /test
      headers:
      - name: x-test-invalid-header
        type: RegularExpression
        value: "[invalid-regex"  ## RDS validation will fail on this invalid regex
      - name: x-test-valid-header
        type: RegularExpression
        value: ".*[valid]"  # Valid regex pattern that will be ignored by RDS validation
    backendRefs:
    - name: test-service
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: gwtest
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: test
