apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route
spec:
  parentRefs:
  - name: example-gateway
  rules:
  - backendRefs:
    - name: backend
      group: gateway.kgateway.dev
      kind: Backend
    filters:
      - type: URLRewrite
        urlRewrite:
          hostname: www.google.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
spec:
  gatewayClassName: kgateway
  listeners:
  - name: http
    protocol: HTTP
    port: 8080
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: backend
  namespace: default
spec:
  type: Static
  static:
    hosts:
      - host: www.google.com
        port: 443 
---
kind: BackendConfigPolicy
apiVersion: gateway.kgateway.dev/v1alpha1
metadata:
  name: backend-tls-policy
spec:
  targetRefs:
    - name: backend
      group: gateway.kgateway.dev
      kind: Backend
  tls:
    insecureSkipVerify: true
    sni: www.google.com