apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
spec:
  gatewayClassName: example-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - name: rule0
    matches:
    - path:
        type: PathPrefix
        value: /example-route
    backendRefs:
    - name: example-svc
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route-2
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - name: rule0
    matches:
    - path:
        type: PathPrefix
        value: /example-route-2
    backendRefs:
    - name: example-svc
      port: 80
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: rate-limit
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: example-route
  rateLimit:
    local:
      tokenBucket:
        maxTokens: 99
        tokensPerFill: 1
        fillInterval: 33s
    global:
      descriptors:
      - entries:
        - type: Path
      extensionRef:
        name: global-ratelimit
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: rate-limit-2
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: example-route-2
  rateLimit:
    local:
      tokenBucket:
        maxTokens: 99
        tokensPerFill: 1
        fillInterval: 33s
    global:
      descriptors:
      - entries:
        - type: Path
      extensionRef:
        name: global-ratelimit-2
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: global-ratelimit
spec:
  type: RateLimit
  rateLimit:
    grpcService:
      backendRef:
        name: ratelimit
        port: 8081
      requestTimeout: 200ms # this timeout is specific to the grpcService
    domain: "api-gateway"
    timeout: "50ms"
    failOpen: true # true is CRD default, but setting explicitly for translator test
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: global-ratelimit-2
spec:
  type: RateLimit
  rateLimit:
    grpcService:
      backendRef:
        name: ratelimit
        port: 8081
      requestTimeout: 200ms # this timeout is specific to the grpcService
    domain: "api-gateway"
    timeout: "50ms"
    failOpen: false
---
apiVersion: v1
kind: Service
metadata:
  name: ratelimit
spec:
  ports:
  - port: 8081
    name: grpc
    targetPort: 8081
    appProtocol: kubernetes.io/h2c
  selector:
    app: ratelimit
---
apiVersion: v1
kind: Service
metadata:
  name: example-svc
spec:
  selector:
    test: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: test